### ISSUE TITLE
Errors occurred in react-select

### ISSUE THREAD

**Issue by lvitaly** [payalabs/scalajs-react-bridge#11]
Hi, 
I've tried to use [react-select](https://github.com/JedWatson/react-select) component through react bridge but got errors.
```
Uncaught Error: Cannot find module 'react-dom'
Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components). Check the render method of `ItemsPage`.
Uncaught Error: Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. Check the render method of `ItemsPage`.
Uncaught TypeError: Cannot read property 'remove' of undefined
```
I've created [repo with example](https://github.com/lvitaly/scalajs-react-select-example) for easy reproduce.
Thanks.

**Comment by ramnivas** [comment]
I tried the example app you provided. I am getting the same error even when I remove the `scalajs-react-bridge` dependency (along with the `Select` component). So the issue seems to be with how react dependencies are pulled in and not with `scalajs-react-bridge`. I don't have much experience with js dependencies through build.sbt (I use webpack instead as shown in https://github.com/payalabs/scalajs-react-bridge-example).

I am closing the issue since it seems unrelated to scalajs-react-bridge.
